### PR TITLE
Updated composer deps - fixes lowest version and drops PHP 5.5

### PR DESCRIPTION
**Pull request by asgrim**
Follows on from #145 to fix up all other dependency versions

### CODE REVIEW

**Comment by BassemN** [comment]
Hi,
PHP 5.5 is currently supported until 10 Jul 2016 so why you will drop it now?

**Comment by asgrim** [comment]
@BassemN PHP 5.5 is not actively supported, it is in security-only phase. If you need to use earlier versions of PHP, then browscap-php will still work, and also receive security fixes for now.

**Comment by asgrim** [comment]
See: http://php.net/supported-versions.php

**Comment by asgrim** [comment]
@mimmi20 all clear from me, assigned to you for review & merge please

**Comment by mimmi20** [comment]
@asgrim Is there a problem with leaving `nightly`?

**Comment by asgrim** [comment]
No particular problem, just don't think it's necessary now 7.0 is stable;
it was only in there to ensure forward compatibility before GA, but we're
there now :)

**Comment by mimmi20** [comment]
@asgrim It is merged.

**Comment by mimmi20** [comment]
@asgrim We should drop support for PHP 5.5 in browscap/browscap too.

**Comment by asgrim** [comment]
Yup, may as well; it's a generation tool rather than a library, so even
better :)

**Pull request merged**
