### PR TITLE
add return codes for commands

### LINKED ISSUE #241: `check-update` command should return a sensible exit code
Is there an automated way to test for a new version? Right no I use `browscap:check-update` but that seems to output only something human-readable:

```
[2018-01-23 12:24:31] there is no newer version available {"memory_peak_usage":"5 MB"}
```

Or:

```
[2018-01-23 12:22:11] there is no cached version available, please update from remote {"memory_peak_usage":"4 MB"}
```

It would be great to test the output of these comments from a script. Now I always execute a memory-heavy `browscap:convert` because I don't know whether it is needed.

### PR DESCRIPTION
**Pull request by mimmi20**
Fixes #241.

### CODE REVIEW

**Comment by asgrim** [comment]
@mimmi20 why close this?

**Comment by mimmi20** [comment]
@asgrim I wanted to write some tests to increase codecoverage. But I think to do this in a separarte PR.

**Comment by asgrim** [comment]
@mimmi20 are the tests related to this PR?

**Comment by mimmi20** [comment]
@asgrim No, general tests for everythings.

**Comment by asgrim** [comment]
Yeah that's fine to do in a separate PR :) just related tests are necessary here

**Comment by mimmi20** [comment]
@asgrim Do you have time to review this again?

**Comment by asgrim** [comment]
Thanks!

**Pull request merged**
