### PR TITLE
remove validation and some direct dependencies

### LINKED ISSUE #248: Remove some direct dependencies
Actually we have some direct dependencies to Symfony's CLI application and to the Doctrine Cache.

If the CLI functions are not required or a different Cache should be used, these dependencies just blow up the required space.

I would like to remove these libraries as direct dependencies and move them to the dev-dependencies and the suggest section.

### LINKED ISSUE #249: Remove validation
Actually inside this library the values from the ini files are validated. 

To implement issue browscap/browscap#1888 this validation have to removed.

Important notice: This validation is also in the version 3 available and should be removed there too.

### PR DESCRIPTION
**Pull request by mimmi20**
This PR wants to remove the property validation and move some direct dependencies to dev and suggest.

Fixes #248 
Fixes #249

### CODE REVIEW

**Comment by asgrim** [comment]
@mimmi20 as this has a BC break, could you rebase against the `5.0.x` branch please (although, it probably makes sense to merge #323 before rebasing so you have the GH Actions build!)

**Comment by mimmi20** [comment]
I rebase against the current 5.0.x Branch

**Comment by asgrim** [comment]
@mimmi20 I merges the other PR now 😁

**Comment by mimmi20** [comment]
I rebased it again, but I can not check the errors locally, as I still require PHP 7.1.

**Comment by asgrim** [comment]
@mimmi20 what about running in Docker? :grin:

**Comment by mimmi20** [comment]
I tried it once on my Windows, but I disabled it as it created issues with booting and more.

**Comment by mimmi20** [comment]
I'll close this PR as I can not test this without support for the dropped PHP versions

**Comment by asgrim** [comment]
OK, will release 5.0.0 then :)

**Pull request closed without merging**
