### PR TITLE
Widen monolog constraint to include 2.0

### LINKED ISSUE #262: Update monolog/monolog dependency
Hello, we are using monolog/monolog package in our application.

We would love to keep packages up to date and update to version 2.0, as `composer outdated` command reports
```
- monolog/monolog (1.25.1) latest is 2.0.0
```

But because of this:
```
browscap/browscap-php        4.2.0    requires  monolog/monolog (^1.23)
```
we are unable to.

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #262

### CODE REVIEW

**Comment by dsazup** [comment]
Any chance this will be merged soon?

**Comment by asgrim** [comment]
Thanks for the ping @dsazup !

**Comment by asgrim** [comment]
This is released in [4.2.1](https://github.com/browscap/browscap-php/releases/tag/4.2.1) :+1:

**Comment by JanMikes** [comment]
Thank you! :+1:

**Pull request merged**
