### PR TITLE
Allow PHP 7.4

### PR DESCRIPTION
**Pull request by holtkamp**
As required for https://github.com/browscap/browscap-php/issues/265

### CODE REVIEW

**Comment by mimmi20** [comment]
This PR is blocked by #270.

**Comment by mimmi20** [comment]
@holtkamp Could you update your branch from master?

**Comment by holtkamp** [comment]
@mimmi20 done, unfortunately this resulted in a second commit. When trying to these two commits into one, I noticed "dependabot" also added a third commit. I am afraid of messing up by squashing, my git skills are still not sufficient for this kind of magic 😟

**Comment by holtkamp** [comment]
Thanks for merging @mimmi20, would this justify a new tagged patch release?

**Comment by mimmi20** [comment]
@asgrim Have you time for this?

**Comment by asgrim** [comment]
Aye should be able to sort it this week hopefully 👍

**Comment by asgrim** [comment]
4.2.2 released: https://github.com/browscap/browscap-php/releases/tag/4.2.2

**Pull request merged**
