### PR TITLE
fix error when switching source file on runtime

### PR DESCRIPTION
**Pull request by mimmi20**
While testing browscap/browscap#615, I got a lot of errors while unit testing after switching the source files. After solving some missing configuration in that test, there were some issues left. 

These are fixed here.

PR browscap/browscap#617 needs this fix to get working.

### CODE REVIEW

**Comment by asgrim** [comment]
Thanks @mimmi20

**Comment by asgrim** [comment]
do we need to tag a release @mimmi20 ?

**Comment by mimmi20** [comment]
I dont think we need a relase for this. For the testing we use dev-master.

**Comment by asgrim** [comment]
:+1:

**Pull request merged**
