### PR TITLE
update readme and dependencies

### LINKED ISSUE #226: How to define custom cache directory?
Documentation only mentions how to use custom cache directory with CLI commands, but not how to use it within PHP.

### PR DESCRIPTION
**Pull request by mimmi20**
Fixes #226.

I updated the Readme.md to explain how to setup a cache in V4. I also updated the dependencies and fixed the found errors.

### CODE REVIEW

**Comment by mimmi20** [comment]
@asgrim We dont have a `3.x` branch yet. Shall I mention the 3.1 release?

**Comment by asgrim** [comment]
We likely don't need a 3.x branch; going 2=>3 was a major rewrite and BC broke everything; 3=>4 is only really minor BC breaks; I doubt we'll backport any releases to 3.x series, so I don't think we'll need a 3.x branch - it's relatively easy to just upgrade to 4.x.

**Comment by asgrim** [comment]
Please wait for build to pass before merge :+1:

**Comment by mimmi20** [comment]
Is there any reason why I cant see a `Details` link for the trais build?

**Pull request merged**
