### PR TITLE
fix(helper)!: fix *BrowsCapINI file names

### PR DESCRIPTION
**Pull request by frugan-dev**

### CODE REVIEW

**Comment by asgrim** [comment]
Out of interest, is this PR triggered by you receiving HTTP 500 errors? If so, see browscap/browscap-site#444 - there is an unusually high number of requests, which has caused us to reach our DB threshold. Please follow that ticket for updates. Thank you!

**Comment by frugan-dev** [comment]
Hi @asgrim, yesterday the files with a lowercase "c" (e.g. `PHP_BrowscapINI`) gave error 500, while those with a capital "C" (e.g. `PHP_BrowsCapINI`) worked.
Today both give error 500 :cry:

**Comment by asgrim** [comment]
> Hi @asgrim, yesterday the files with a lowercase "c" (e.g. `PHP_BrowscapINI`) gave error 500, while those with a capital "C" (e.g. `PHP_BrowsCapINI`) worked. Today both give error 500 😢

yeah I think that may have just be coincidence; maybe one was cached at the time by Cloudflare. I think it is likely this is the same issue, so going to close this (i.e. it isn't case sensitive, so this shouldn't be an issue!)

Thanks

**Comment by asgrim** [comment]
Duplicate of browscap/browscap-site#444

**Pull request closed without merging**
