### PR TITLE
PHP 8.0 support, drop PHP 7.1/7.2, and Travis build

### LINKED ISSUE #318: Add github actions instead of Travis CI
We've migrated browscap-site and browscap itself to GH actions for the CI build, so we should do the same here eventually.

### LINKED ISSUE #320: Add support for PHP 8 // Project still alive?
Hello,

I wanted to ask whether this project is still alive and we want to bring in support for PHP 8?

Thanks for info.

### PR DESCRIPTION
**Pull request by asgrim**
**NOTE** - whilst no technical BC breaks, we are dropping support for PHP 7.1 and 7.2, so this will be tagged `5.0.0`.

Fixes #318 
Fixes #320

### CODE REVIEW

**Comment by asgrim** [comment]
Hold fire on merge, I'm just checking on the behaviour of `laminas/automatic-releases` with regards to new major releases :)

**Comment by asgrim** [comment]
Updated trunk to `5.0.x` so this can be merged once approved :+1:

**Review by mimmi20 — APPROVED** [review]

**Comment by asgrim** [comment]
Thanks so much @duxthefux and @mimmi20 !

**Comment by duxthefux** [comment]
awesome thx a lot! 

do you mind creating a new release? thanks!

**Comment by asgrim** [comment]
We will do yep, need to review another PR (#267) as it has BC breaks too so want to get them in before 5.0.0 release :)

**Pull request merged**
