### PR TITLE
Travis cache 2.x

### PR DESCRIPTION
**Pull request by asgrim**
Use the browscap.ini caching mentioned in #99 but on the 2.x branch (5.3 and 5.4 are also no longer allowed to fail)

### CODE REVIEW

**Comment by asgrim** [comment]
@mimmi20 could you review & merge please? :)

**Comment by mimmi20** [comment]
@asgrim This looks fine. Do I have the right to merge?

**Comment by asgrim** [comment]
Do you have the merge button? :)

**Comment by mimmi20** [comment]
No, Idont have one.

**Comment by asgrim** [comment]
You should now ^_^

**Pull request merged**
