### PR TITLE
Allow Symfony 6

### LINKED ISSUE #416: Update symfony/console to 6.x.
Hi,

  I'm attempting to use browscap-php in my project, but another package I use requires symfony/console 6.x.  Would you mind adding 6.x as an option so I can use your package?  Thanks!

### PR DESCRIPTION
**Pull request by Slamdunk**
Fixes #416

### CODE REVIEW

**Review by mimmi20 — APPROVED** [review]

**Comment by Slamdunk** [comment]
Regarding the BC Break reported by CI: I think [`BrowscapPHP\Helper\Filesystem`](https://github.com/browscap/browscap-php/blob/6.2.x/src/Helper/Filesystem.php) should be `@internal`

**Comment by Slamdunk** [comment]
Ping @asgrim

**Comment by asgrim** [comment]
@Slamdunk thanks - we'll take this further upstream, even latest BCC tool falters here, I can't think why at the moment (see also #418 )

**Comment by asgrim** [comment]
Yeah, BC breaks are correct here, because we use `extends` for both Symfony Commands and `Filesystem` as you found, then upstream BC breaks are also our own inherited BC breaks. I'm closing this in favour of #418 where a BC break here is necessary to make our own classes `@internal` to avoid this going forward. Thank you!

**Pull request closed without merging**
